# Generated by Django 3.1 on 2020-08-25 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Fashion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('features', models.CharField(max_length=250)),
                ('silhoutte', models.CharField(max_length=250)),
                ('neckline', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=250)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dress.category')),
                ('fashion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dress.fashion')),
            ],
        ),
    ]
