# Generated by Django 3.1 on 2020-08-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0002_auto_20200826_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dress',
            name='on_cart',
            field=models.BooleanField(default=False),
        ),
    ]
