# Generated by Django 3.1 on 2020-08-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0003_auto_20200826_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dress',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]
